In [2]:
import pandas as pd

In [3]:
notas = pd.read_excel(r"C:\\Users\\201077405\\Documents\\Projetos\\New_Sistema\\Cargas_Dados\\Carga_de_testes\\8800 Conferência 01.2024 - OK L6.xlsx")

In [5]:
notas.head(1)
# display(notas)

,CONCAT,NUMERO,DATA_FISCAL,NF,ITEM,ITEM_NF,COD_PRODUTO,NCM,DESCRICAO,CHAVE_ACESSO,...,PRECO_LIQUIDO,PRECO_LIQUIDO_SEM_IMPOSTO,PAIS,MOVIMENTO,CATEGORIA_NF,MOEDA,Código para Filtro NF,NF L89,Fluxo,NF L6
0,4458830,44588,2022-12-01,7811,3,30,DTR0000446082,3402.90.19,DTR0000446082 - PREPARACAO PARA LIMPEZA,'35221288309620003254550010000078111074489889',...,665.61585,565.773473,CA,Entrada,NF-e Importação,BRL,7811DTR0000446082,NaN,FL06,NaN

In [16]:
novas_colunas = {'CONCAT': 'Concatenação', 'NUMERO' : 'NUM'}
notas = notas.rename(columns = novas_colunas)
notas.head(1)

,Concatenação,NUM,DATA_FISCAL,NF,ITEM,ITEM_NF,COD_PRODUTO,NCM,DESCRICAO,CHAVE_ACESSO,...,PRECO_LIQUIDO,PRECO_LIQUIDO_SEM_IMPOSTO,PAIS,MOVIMENTO,CATEGORIA_NF,MOEDA,Código para Filtro NF,NF L89,Fluxo,NF L6
0,4458830,44588,2022-12-01,7811,3,30,DTR0000446082,3402.90.19,DTR0000446082 - PREPARACAO PARA LIMPEZA,'35221288309620003254550010000078111074489889',...,665.61585,565.773473,CA,Entrada,NF-e Importação,BRL,7811DTR0000446082,NaN,FL06,NaN

In [4]:
# ordenar crescente coluna especifica

notas = notas.sort_values(by=['DESCRICAO'])
notas.head(3)

,CONCAT,NUMERO,DATA_FISCAL,NF,ITEM,ITEM_NF,COD_PRODUTO,NCM,DESCRICAO,CHAVE_ACESSO,...,PRECO_LIQUIDO,PRECO_LIQUIDO_SEM_IMPOSTO,PAIS,MOVIMENTO,CATEGORIA_NF,MOEDA,Código para Filtro NF,NF L89,Fluxo,NF L6
5590,16432610,164326,2024-06-06,31443,1,10,1176,7007.21.00,1176 VIDRO DO PARA BRISA UTILIZADO EM,'35240688309620003254550010000314431238145924',...,173.27406,142.968427,CN,Entrada,NF-e Importação,BRL,314431176,NaN,NaN,4101321461-10
5591,16432620,164326,2024-06-06,31443,2,20,1176,7007.21.00,1176 VIDRO DO PARA BRISA UTILIZADO EM,'35240688309620003254550010000314431238145924',...,47.26237,38.996181,CN,Entrada,NF-e Importação,BRL,314431176,NaN,NaN,4101321461-10
4459,18244110,182441,2024-08-05,34719,1,10,1274,3919.10.90,1274 FITA ZEBRADA PO4101311740 ITEM,'35240888309620003254550010000347191256751930',...,11123.41474,6729.665918,FR,NF-e Importação,NF-e Importação,BRL,347191274,NaN,NaN,4101311740-10

In [5]:
# ordenar crescente coluna especifica

notas = notas.sort_values(by=['DESCRICAO'],ascending= False)
notas.head(3)

,CONCAT,NUMERO,DATA_FISCAL,NF,ITEM,ITEM_NF,COD_PRODUTO,NCM,DESCRICAO,CHAVE_ACESSO,...,PRECO_LIQUIDO,PRECO_LIQUIDO_SEM_IMPOSTO,PAIS,MOVIMENTO,CATEGORIA_NF,MOEDA,Código para Filtro NF,NF L89,Fluxo,NF L6
3244,5335210,53352,2023-02-06,36375,1,10,DTR0000335163,7318.15.00,WOOD SCREW FZ M6X20-12,'35230254801378000113550010000363751270088010',...,2.05,1.727125,BR,Entrada,NF-e Entrada (MIRO),BRL,36375DTR0000335163,NaN,FL06,NaN
6516,17398810,173988,2024-07-04,36549,1,10,DTR0000492243,8544.60.00,WIRE EN50382 2 3600V1X185 F 120XZ,'35240630983200000172550010000365491282807321',...,252.05,220.543750,BR,Entrada,NF-e Entrada (MIRO),BRL,36549DTR0000492243,NaN,FL05,5600130663-20
1207,9781810,97818,2023-10-19,58748,1,10,DTR0000492219,8544.49.00,WIRE EN50264-3-1 600V 35 M,'35231002006282000160550010000587481738724000',...,20.03,20.030000,BR,Entrada,NF-e Entrada (MIRO),BRL,58748DTR0000492219,NaN,FL05,NaN

In [6]:
notas = notas.sort_values(by=['NF'],ascending= True)
notas.head(3)

,CONCAT,NUMERO,DATA_FISCAL,NF,ITEM,ITEM_NF,COD_PRODUTO,NCM,DESCRICAO,CHAVE_ACESSO,...,PRECO_LIQUIDO,PRECO_LIQUIDO_SEM_IMPOSTO,PAIS,MOVIMENTO,CATEGORIA_NF,MOEDA,Código para Filtro NF,NF L89,Fluxo,NF L6
2060,76912120,76912,2023-07-10,7,12,120,DTR0009907545,7318.15.00,PARAF HSC M6X20 ZN 0 15,'35221288309620003840550010000000071645852254',...,0.05,0.05,BR,Entrada,NF-e Entrada (MIRO),BRL,7DTR0009907545,NaN,FL06,NaN
2062,76912150,76912,2023-07-10,7,15,150,DTR0009907859,7318.15.00,PARAFUSO HEX M8X60 FLZN 0 15,'35221288309620003840550010000000071645852254',...,0.34,0.34,BR,Entrada,NF-e Entrada (MIRO),BRL,7DTR0009907859,NaN,FL06,NaN
2061,76912130,76912,2023-07-10,7,13,130,DTR0009907557,7318.15.00,PARAF CAB CIL ISO4762 M8X25 8 8 ZFL,'35221288309620003840550010000000071645852254',...,0.32,0.32,BR,Entrada,NF-e Entrada (MIRO),BRL,7DTR0009907557,NaN,FL06,NaN

In [7]:
notas = notas.sort_values(by=['NF'],ascending= False)
notas.head(3)

,CONCAT,NUMERO,DATA_FISCAL,NF,ITEM,ITEM_NF,COD_PRODUTO,NCM,DESCRICAO,CHAVE_ACESSO,...,PRECO_LIQUIDO,PRECO_LIQUIDO_SEM_IMPOSTO,PAIS,MOVIMENTO,CATEGORIA_NF,MOEDA,Código para Filtro NF,NF L89,Fluxo,NF L6
7859,161264100,161264,2024-05-27,1007253,10,100,1040,3917.32.90,ESPAGUETE TERMO RETRATIL 39173229,'35240202545405000130550040010072531423658751',...,473.152,473.152000,BR,Entrada,NF-e Entrada (MIRO),BRL,10072531040,NaN,NaN,4101175312-100
9052,19760010,197600,2024-10-08,958629,1,10,AR00000248178,8607.99.00,ESTRUTURA BOGIE MOTOR MSP L6,'35240956563976000127550030009586291946679703',...,105483.810,95726.557575,BR,Entrada,NF-e Entrada (MIRO),BRL,958629AR00000248178,NaN,FL02,5600113419-20
9051,19760310,197603,2024-10-08,958628,1,10,AR00000248178,8607.99.00,ESTRUTURA BOGIE MOTOR MSP L6,'35240956563976000127550030009586281904743023',...,105483.810,95726.557575,BR,Entrada,NF-e Entrada (MIRO),BRL,958628AR00000248178,NaN,FL02,5600113419-20